obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_BATTERY_MAX77696)	+= max77696-battery.o
obj-$(CONFIG_CHARGER_MAX77696)	+= max77696-charger.o
obj-$(CONFIG_EH_MAX77696)	+= max77696-eh.o